# Generated by Django 4.1.2 on 2022-11-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=25)),
                ("lastname", models.CharField(max_length=25)),
                ("date_of_birth", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("gender", models.CharField(max_length=7)),
                ("phonenumber", models.IntegerField()),
            ],
        ),
    ]
