# Generated by Django 4.1.2 on 2022-11-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HelloWorld", "0002_user1_confirmpwd_user1_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=25)),
                ("lastname", models.CharField(max_length=25)),
                ("phonenumber", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("occupation", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=50)),
                ("document_status", models.CharField(max_length=50)),
                ("account_number", models.IntegerField()),
            ],
        ),
    ]
