# Generated by Django 4.1.2 on 2022-12-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HelloWorld", "0003_personalinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="personal_Info_Status",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
